### PR TITLE
Allow custom component order and custom functions

### PR DESCRIPTION
**Pull request by DriesOlbrechts**
This PR attempts to add some configurability to the statusline.

In addition to being able to choose the order in which components are displayed, it makes custom components possible by allowing functions in the config.

As an example, adding your own git blame text.
```lua
components = {
	"mode",
	" ",
	"path",
	" ",
	"git",
	"%=",
	function()
	  local git_blame = require("gitblame")
	  if git_blame.is_blame_text_available() then
            return git_blame.get_current_blame_text()
	  else
            return ""
	  end
	end,
	"%=",
	"diagnostics",
	" ",
	"filetype_lsp",
	" ",
	"progress",
	" ",
},
```

I'm happy to hear any notes/suggestions.

For example not quite happy with how seperators are now done in custom config.
Perhaps special string identifiers like `'spaces.left'` could be converted to the config value.

I don't want to intrude into your personal project, so feel free to just close my PR if that's the case!

### CODE REVIEW

**Comment by sschleemilch** [comment]
:rocket: Thank for that contribution, it looks pretty good and I would love to see that merged soon since it increases the flexibility for users a lot :heart: 

> For example not quite happy with how seperators are now done in custom config.
Perhaps special string identifiers like 'spaces.left'

I just checked out your main and had a look. The `spaces.components` option is indeed problematic and is not respected anymore.
However, I think I have a proposal for that one.
How about we let the user configure the components but not the spacing stuff?

E.g. we could say the components config part looks like that (default)

```lua
components = {
  left = {
    'mode',
    'path',
    'git'
  },
  right = {
    'diagnostics',
    'filetype_lsp',
    'progress'
  }
}
```

If we do that, that we can build up the statusline string afterwards and take config spacing options. Seems like we are looping anyway now in `render()`. We then just need to have two loops over left and right components.

here is a patch that would work. Let me know what you think

```patch
diff --git a/lua/slimline/components.lua b/lua/slimline/components.lua
index 7b4237b..594c0c9 100644
--- a/lua/slimline/components.lua
+++ b/lua/slimline/components.lua
@@ -80,7 +80,7 @@ function M.mode(config)
   if config.sep.hide.first then
     sep_left = ''
   end
-  return highlights.highlight_content(content, M.get_mode_hl(mode), sep_left, config.sep.right)
+  return highlights.highlight_content(content, M.get_mode_hl(), sep_left, config.sep.right)
 end
 
 --- Git component showing branch
@@ -241,7 +241,6 @@ end
 --- @param config table
 --- @return string
 function M.progress(config)
-  local mode = M.get_mode()
   local cur = vim.fn.line('.')
   local total = vim.fn.line('$')
   local content = ''
@@ -257,7 +256,7 @@ function M.progress(config)
   if config.sep.hide.last then
     sep_right = ''
   end
-  return highlights.highlight_content(content, M.get_mode_hl(mode), config.sep.left, sep_right)
+  return highlights.highlight_content(content, M.get_mode_hl(), config.sep.left, sep_right)
 end
 
 return M
diff --git a/lua/slimline/default_config.lua b/lua/slimline/default_config.lua
index c1cb9f9..a663982 100644
--- a/lua/slimline/default_config.lua
+++ b/lua/slimline/default_config.lua
@@ -21,18 +21,16 @@ local function create_M()
   }
 
   M.components = {
-    'mode',
-    M.spaces.components,
-    'path',
-    M.spaces.components,
-    'git',
-    '%=',
-    'diagnostics',
-    M.spaces.components,
-    'filetype_lsp',
-    M.spaces.components,
-    'progress',
-    M.spaces.right,
+    left = {
+      'mode',
+      'path',
+      'git',
+    },
+    right = {
+      'diagnostics',
+      'filetype_lsp',
+      'progress',
+    },
   }
 
   M.hl = {
@@ -50,16 +48,16 @@ local function create_M()
 
   M.icons = {
     diagnostics = {
-      ERROR = ' ',
-      WARN = ' ',
-      HINT = ' ',
-      INFO = ' ',
+      ERROR = ' ',
+      WARN = ' ',
+      HINT = ' ',
+      INFO = ' ',
     },
     git = {
-      branch = '',
+      branch = '',
     },
-    folder = ' ',
-    lines = ' ',
+    folder = ' ',
+    lines = ' ',
   }
 
   return M
diff --git a/lua/slimline/init.lua b/lua/slimline/init.lua
index 807334d..220728d 100644
--- a/lua/slimline/init.lua
+++ b/lua/slimline/init.lua
@@ -24,24 +24,54 @@ local function resolve_component(component_name, config)
   end
 end
 
+-- Concats resolved components with given spacing
+---comment
+---@param comps table
+---@param spacing string
+---@return string
+function M.concat_components(comps, spacing)
+  local result = ''
+  local first = true
+  for _, c_fn in ipairs(comps) do
+    local space = spacing
+    if first then
+      space = ''
+    end
+    if type(c_fn) == 'function' then
+      result = result .. space .. c_fn()
+    elseif type(c_fn) == 'string' then
+      result = result .. space .. c_fn
+    end
+  end
+  return result
+end
+
 --- Renders the statusline.
 ---@return string
 function M.render()
   local config = vim.g.slimline_config
-  if not config or not config.resolved_components then
+  if not config or not config.components.left or not config.components.right then
     return ''
   end
 
   local result = '%#Slimline#' .. config.spaces.left
-  -- call the functions in resolved_components and add them to the statusline string
-  for _, component_func in ipairs(config.resolved_components) do
-    if type(component_func) == 'function' then
-      result = result .. component_func()
-    elseif type(component_func) == 'string' then
-      result = result .. component_func
-    end
-  end
+  result = result .. M.concat_components(config.components.left, config.spaces.components)
+  result = result .. '%='
+  result = result .. M.concat_components(config.components.right, config.spaces.components)
+  result = result .. config.spaces.right
+
+  return result
+end
 
+-- Resolving components into a table
+---@param comps table
+---@param opts table
+---@return table
+local function resolve_components(comps, opts)
+  local result = {}
+  for _, component in ipairs(comps) do
+    table.insert(result, resolve_component(component, opts))
+  end
   return result
 end
 
@@ -57,12 +87,10 @@ function M.setup(opts)
     opts.sep.left = ''
     opts.sep.right = ''
   end
+
   -- Resolve component references
-  local resolved_components = {}
-  for _, component in ipairs(opts.components) do
-    table.insert(resolved_components, resolve_component(component, opts))
-  end
-  opts.resolved_components = resolved_components
+  opts.components.left = resolve_components(opts.components.left, opts)
+  opts.components.right = resolve_components(opts.components.right, opts)
 
   vim.g.slimline_config = opts
   local hl = require('slimline.highlights')

```

**Comment by DriesOlbrechts** [comment]
> 🚀 Thank for that contribution, it looks pretty good and I would love to see that merged soon since it increases the flexibility for users a lot ❤️
> 
> > For example not quite happy with how seperators are now done in custom config.
> > Perhaps special string identifiers like 'spaces.left'
> 
> I just checked out your main and had a look. The `spaces.components` option is indeed problematic and is not respected anymore. However, I think I have a proposal for that one. How about we let the user configure the components but not the spacing stuff?
> 
> E.g. we could say the components config part looks like that (default)
> 
> ```lua
> components = {
>   left = {
>     'mode',
>     'path',
>     'git'
>   },
>   right = {
>     'diagnostics',
>     'filetype_lsp',
>     'progress'
>   }
> }
> ```
> 
> If we do that, that we can build up the statusline string afterwards and take config spacing options. Seems like we are looping anyway now in `render()`. We then just need to have two loops over left and right components.
> 
> here is a patch that would work. Let me know what you think
> 
> ```diff
> diff --git a/lua/slimline/components.lua b/lua/slimline/components.lua
> index 7b4237b..594c0c9 100644
> --- a/lua/slimline/components.lua
> +++ b/lua/slimline/components.lua
> @@ -80,7 +80,7 @@ function M.mode(config)
>    if config.sep.hide.first then
>      sep_left = ''
>    end
> -  return highlights.highlight_content(content, M.get_mode_hl(mode), sep_left, config.sep.right)
> +  return highlights.highlight_content(content, M.get_mode_hl(), sep_left, config.sep.right)
>  end
>  
>  --- Git component showing branch
> @@ -241,7 +241,6 @@ end
>  --- @param config table
>  --- @return string
>  function M.progress(config)
> -  local mode = M.get_mode()
>    local cur = vim.fn.line('.')
>    local total = vim.fn.line('$')
>    local content = ''
> @@ -257,7 +256,7 @@ function M.progress(config)
>    if config.sep.hide.last then
>      sep_right = ''
>    end
> -  return highlights.highlight_content(content, M.get_mode_hl(mode), config.sep.left, sep_right)
> +  return highlights.highlight_content(content, M.get_mode_hl(), config.sep.left, sep_right)
>  end
>  
>  return M
> diff --git a/lua/slimline/default_config.lua b/lua/slimline/default_config.lua
> index c1cb9f9..a663982 100644
> --- a/lua/slimline/default_config.lua
> +++ b/lua/slimline/default_config.lua
> @@ -21,18 +21,16 @@ local function create_M()
>    }
>  
>    M.components = {
> -    'mode',
> -    M.spaces.components,
> -    'path',
> -    M.spaces.components,
> -    'git',
> -    '%=',
> -    'diagnostics',
> -    M.spaces.components,
> -    'filetype_lsp',
> -    M.spaces.components,
> -    'progress',
> -    M.spaces.right,
> +    left = {
> +      'mode',
> +      'path',
> +      'git',
> +    },
> +    right = {
> +      'diagnostics',
> +      'filetype_lsp',
> +      'progress',
> +    },
>    }
>  
>    M.hl = {
> @@ -50,16 +48,16 @@ local function create_M()
>  
>    M.icons = {
>      diagnostics = {
> -      ERROR = ' ',
> -      WARN = ' ',
> -      HINT = ' ',
> -      INFO = ' ',
> +      ERROR = ' ',
> +      WARN = ' ',
> +      HINT = ' ',
> +      INFO = ' ',
>      },
>      git = {
> -      branch = '',
> +      branch = '',
>      },
> -    folder = ' ',
> -    lines = ' ',
> +    folder = ' ',
> +    lines = ' ',
>    }
>  
>    return M
> diff --git a/lua/slimline/init.lua b/lua/slimline/init.lua
> index 807334d..220728d 100644
> --- a/lua/slimline/init.lua
> +++ b/lua/slimline/init.lua
> @@ -24,24 +24,54 @@ local function resolve_component(component_name, config)
>    end
>  end
>  
> +-- Concats resolved components with given spacing
> +---comment
> +---@param comps table
> +---@param spacing string
> +---@return string
> +function M.concat_components(comps, spacing)
> +  local result = ''
> +  local first = true
> +  for _, c_fn in ipairs(comps) do
> +    local space = spacing
> +    if first then
> +      space = ''
> +    end
> +    if type(c_fn) == 'function' then
> +      result = result .. space .. c_fn()
> +    elseif type(c_fn) == 'string' then
> +      result = result .. space .. c_fn
> +    end
> +  end
> +  return result
> +end
> +
>  --- Renders the statusline.
>  ---@return string
>  function M.render()
>    local config = vim.g.slimline_config
> -  if not config or not config.resolved_components then
> +  if not config or not (config.components.left or config.components.right) then
>      return ''
>    end
>  
>    local result = '%#Slimline#' .. config.spaces.left
> -  -- call the functions in resolved_components and add them to the statusline string
> -  for _, component_func in ipairs(config.resolved_components) do
> -    if type(component_func) == 'function' then
> -      result = result .. component_func()
> -    elseif type(component_func) == 'string' then
> -      result = result .. component_func
> -    end
> -  end
> +  result = result .. M.concat_components(config.components.left, config.spaces.components)
> +  result = result .. '%='
> +  result = result .. M.concat_components(config.components.right, config.spaces.components)
> +  result = result .. config.spaces.right
> +
> +  return result
> +end
>  
> +-- Resolving components into a table
> +---@param comps table
> +---@param opts table
> +---@return table
> +local function resolve_components(comps, opts)
> +  local result = {}
> +  for _, component in ipairs(comps) do
> +    table.insert(result, resolve_component(component, opts))
> +  end
>    return result
>  end
>  
> @@ -57,12 +87,10 @@ function M.setup(opts)
>      opts.sep.left = ''
>      opts.sep.right = ''
>    end
> +
>    -- Resolve component references
> -  local resolved_components = {}
> -  for _, component in ipairs(opts.components) do
> -    table.insert(resolved_components, resolve_component(component, opts))
> -  end
> -  opts.resolved_components = resolved_components
> +  opts.components.left = resolve_components(opts.components.left, opts)
> +  opts.components.right = resolve_components(opts.components.right, opts)
>  
>    vim.g.slimline_config = opts
>    local hl = require('slimline.highlights')
> ```

This is definitely a lot better.
I added a center segment just in case people want something there.
I also fixed an issue where `first` was never set to false.

Let me know what you think!

**Comment by sschleemilch** [comment]
It crashes when switching a colorscheme.
We also need:

```patch
diff --git a/lua/slimline/autocommands.lua b/lua/slimline/autocommands.lua
index cf89a56..8a4194b 100644
--- a/lua/slimline/autocommands.lua
+++ b/lua/slimline/autocommands.lua
@@ -19,6 +19,6 @@ vim.api.nvim_create_autocmd('Colorscheme', {
   callback = function()
     local hl = require('slimline.highlights')
     hl.hl_cache = {}
-    hl.create()
+    hl.create(vim.g.slimline_config)
   end,
 })
```

Also missing the center component resolving:
```patch
diff --git a/lua/slimline/init.lua b/lua/slimline/init.lua
index 367a294..39c8e9a 100644
--- a/lua/slimline/init.lua
+++ b/lua/slimline/init.lua
@@ -93,6 +93,7 @@ function M.setup(opts)
 
   -- Resolve component references
   opts.components.left = resolve_components(opts.components.left, opts)
+  opts.components.center = resolve_components(opts.components.center, opts)
   opts.components.right = resolve_components(opts.components.right, opts)
 
   vim.g.slimline_config = opts
```

Now that we can rearrange components (which is good), we have a problem with the `sep.hide.first` functionality:
image

I think we need to pass the info whether a component is first or last to the `resolve_component()`.
Maybe like this:

```lua
local function resolve_components(comps, opts, group_position)
  local result = {}
  for i, component in ipairs(comps) do
    local position = nil
    if group_position == 'left' and i == 1 then
      position = 'first'
    elseif group_position == 'right' and i == #comps then
      position = 'last'
    end
    table.insert(result, resolve_component(component, opts, position))
  end
  return result
end
```
in there we can pass it to `return components[component_name](config, position, ...)`

And then something like this

```lua
local function get_sep_or_empty(sep, sep_location, component_position, hide_cfg)
  local result = sep
  if component_position == 'first' and sep_location == 'left' and hide_cfg.first then
    result = ''
  elseif component_position == 'last' and sep_location == 'right' and hide_cfg.last then
    result = ''
  end
  return result
end

--- Mode component
--- @param config table
--- @param position string? -- "first"|"last"|nil
--- @return string
function M.mode(config, position)
  local mode = M.get_mode()
  local render = mode
  if config.verbose_mode == false then
    render = string.sub(mode, 1, 1)
  end
  local content = ' ' .. render .. ' '
  local sep_left = get_sep_or_empty(config.sep.left, 'left', position, config.sep.hide)
  local sep_right = get_sep_or_empty(config.sep.right, 'right', position, config.sep.hide)
  return highlights.highlight_content(content, M.get_mode_hl(), sep_left, sep_right)
end
```

Don't know... a bit fiddely :D

**Comment by DriesOlbrechts** [comment]
@sschleemilch 
Good spot :smile:.
I came up with a slightly different solution, let me know which one you prefer!

I check the seperators in `resolve_component` now , then pass a `sep` object to the component functions.
Using a static `position` variable to keep track of the position in the statusline.

**Comment by sschleemilch** [comment]
> @sschleemilch Good spot 😄. I came up with a slightly different solution, let me know which one you prefer!
> 
> I check the seperators in `resolve_component` now , then pass a `sep` object to the component functions. Using a static `position` variable to keep track of the position in the statusline.

Your solution is way better than my proposal. Good job.

There are some slight things that will not be consistent anymore after we merge it. Well, namely just one:
I had in mind that left components "grow" to the center regarding on what side their "secondary" part is and turn this around on the right side. Right now the only component this affects is `filetype_lsp` progress though:

image

But I think I will throw away that idea and make the secondary part of the component also to the right side, then we do not have a problem.

**Review by sschleemilch — APPROVED** [review]

**Comment by DriesOlbrechts** [comment]
> > @sschleemilch Good spot 😄. I came up with a slightly different solution, let me know which one you prefer!
> > I check the seperators in `resolve_component` now , then pass a `sep` object to the component functions. Using a static `position` variable to keep track of the position in the statusline.
> 
> Your solution is way better than my proposal. Good job.
> 
> There are some slight things that will not be consistent anymore after we merge it. Well, namely just one: I had in mind that left components "grow" to the center regarding on what side their "secondary" part is and turn this around on the right side. Right now the only component this affects is `filetype_lsp` progress though:
> 
> image
> 
> But I think I will throw away that idea and make the secondary part of the component also to the right side, then we do not have a problem.

Definitely something to keep in mind as a potential future feature!

**Pull request merged**
